# Tensor Parameters
Any tensor can be identified with the help of the following three parameters:

- Rank: This specifies the number of dimensions of the tensor.
- Shape: The number of rows and columns in a tensor.
- Type: The datatype that is carried by the tensor.

Tensors can be built using NumPy arrays and can be converted into a tensor object.

# One Dimension Tensors

In [1]:
import numpy as np
tensor_1d = np.array([1,2,3,4,5])
print (tensor_1d)

[1 2 3 4 5]


In [2]:
print (tensor_1d.ndim)

1


In [3]:
print (tensor_1d.shape)
print (tensor_1d.dtype)

(5,)
int64


In [4]:
import tensorflow as tf 

tensor_1d = tf.convert_to_tensor(tensor_1d, dtype=tf.int64)

tf.print(tensor_1d)
tf.print(tensor_1d[0])
tf.print(tensor_1d[1])

[1 2 3 4 5]
1
2


# Two Dimension Tensors

In [5]:
array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')

print(array_2d_1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
array_2d_1.ndim

2

In [7]:
array_2d_1.shape

(4, 4)

In [8]:
array_2d_1.dtype

dtype('int32')

In [9]:
tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
print(tensor_2d_1)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int32)


# Matrix Operations with Tensors
TensorFlow 2.0 supports all the matrix operations, such as:

- Addition
- Dot product
- Matrix multiplication
- Determinant

In [10]:
#Matrix Addition
#Initializing the Array

array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
array_2d_2 = np.array(np.arange(16,32).reshape(4,4), dtype='int32')

#Converting to Tensors

tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

#Matrix Operation

mat_add = tf.math.add(tensor_2d_1, tensor_2d_2)

#Printing the Result

print(mat_add)

tf.Tensor(
[[16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]], shape=(4, 4), dtype=int32)


In [12]:
#Matrix Multiplication
#Initializing the Array

array_2d_1 = np.array(np.arange(16).reshape(4,4), dtype='int32')
array_2d_2 = np.array(np.arange(16,32).reshape(4,4), dtype='int32')

##Converting to Tensors

tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

#Matrix Operation

mat_mul = tf.matmul(tensor_2d_1, tensor_2d_2)

#Printing the Result

print (mat_mul)

tf.Tensor(
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]], shape=(4, 4), dtype=int32)


In [16]:
#Determinant of a Matrix
#Initializing the Array

array_2d_1 = np.array(np.arange(16).reshape(4,4),dtype=float)
print(array_2d_1.dtype)
#Converting to Tensors

tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
print(tensor_2d_1.dtype)
#Matrix Operation

mat_det = tf.linalg.det(tensor_2d_1)

#Printing the Result

print(mat_det)

float64
<dtype: 'float64'>
tf.Tensor(-2.9582283945788216e-30, shape=(), dtype=float64)


# Linear Regression Model

Building Linear Regression Model - Steps
- Define the relationship between x and y.
- Generate random data points.
- Define a cost function that calculates the error between the actual and predicted values.
- Optimize the cost function using a gradient descent algorithm.
- Iterate the optimization process until the values converge.

In [28]:
import numpy as np
import tensorflow as tf 

#Initializing the number of points and the dependent and independent variables:

numPts = 100
x_train = []
y_train = []

#Assigning the values for a and b:

a = 0.45
b = 0.60

#y = 0.45 * x + 0.60y
#Finally, after gradient descent, the model should also converge to the above values of a and b.

In [29]:
#The following code is used to generate random points for xx and yy based on the relationship defined above.

for i in range(numPts):
    xtemp = np.random.normal(0.0,0.5)
    ytemp = a*xtemp + b +np.random.normal(0.0,0.1)
    x_train.append([xtemp])
    y_train.append([ytemp])

In [31]:
x_train[:5]

[[-0.4487937738554645],
 [1.074674478178114],
 [0.17900464322081963],
 [-0.4256070368421761],
 [0.6035993450581476]]

In [32]:
y_train[:5]

[[0.5074696646888083],
 [1.1608813272280885],
 [0.6150242517944509],
 [0.38343704403101064],
 [1.0369389691891546]]

In [33]:
#Initializing the Variables
#The objective here is to implement a Machine Learning algorithm to predict y given x, using TensorFlow.
#The linear regression model should converge to an optimal a and b that minimizes the cost function.
#Initializing arbitrary values for A and setting b to zero:

A = tf.Variable(tf.random.uniform([1], -1.0, 1.0))
b = tf.Variable(tf.zeros([1]))
#Creating a relationship between x and y:

def h(x):
    y = A*x + b
    return y


In [38]:
#Define Cost Function
#The following code is used to set the learning rate. It can be set to any number between 0 and 1.

learningRate = 0.25
#The cost function is defined as follows.

def squared_error(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

In [42]:
#Optimize Cost Function And Iterate Optimization
#Here, the optimization process is iterated using gradient descent. Finally, the model is trained to minimize the cost function, and the model is tested.

NumIter = 100
for epoch in range(NumIter):
    with tf.GradientTape() as tape:
        y_predicted = h(x_train)
        costF = squared_error(y_predicted, y_train)
				
    gradients = tape.gradient(costF, [A,b])
    #print(gradients)

    A.assign_sub(gradients[0]*learningRate)
    b.assign_sub(gradients[1]*learningRate)

In [43]:
A

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.44740215], dtype=float32)>

In [44]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.5923675], dtype=float32)>

Here, after the iteration of the optimization process, the minimum cost function will be achieved.